# -*- coding: utf-8 -*-
"""
테이블 누름틀 자동 입력 (배치 모드 - 로그 저장)

대화형 입력 없이 자동으로 모든 테이블에 누름틀을 삽입하고 로그를 파일로 저장합니다.
설정: 헤더=1행, 푸터=0행, 작성자=KIM
"""

from table_manager import TableManager
from cursor_utils import get_hwp_instance
import yaml
from datetime import datetime
import sys
import os


def main():
    # 로그 파일 설정
    log_dir = "debugs/logs"
    os.makedirs(log_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = os.path.join(log_dir, f"auto_insert_{timestamp}.log")

    # 로그 파일 열기
    log = open(log_file, 'w', encoding='utf-8')

    def log_print(msg=""):
        """콘솔과 파일에 동시 출력"""
        print(msg)
        log.write(msg + '\n')
        log.flush()

    log_print("=" * 60)
    log_print("  테이블 누름틀 자동 입력 (배치 모드)")
    log_print("=" * 60)
    log_print(f"실행 시간: {timestamp}")
    log_print(f"로그 파일: {log_file}")
    log_print()

    # 설정값
    HEADER_ROWS = 1
    FOOTER_ROWS = 0
    AUTHOR_NAME = "KIM"

    log_print(f"[설정]")
    log_print(f"  - 헤더 행: {HEADER_ROWS}")
    log_print(f"  - 푸터 행: {FOOTER_ROWS}")
    log_print(f"  - 작성자: {AUTHOR_NAME}")
    log_print()

    # 1. 한글 인스턴스 연결
    log_print("[1단계] 한글 인스턴스 연결 중...")
    hwp = get_hwp_instance()
    if not hwp:
        log_print("✗ 오류: 한글이 실행 중이지 않습니다.")
        log_print("  → 한글을 먼저 실행하고 문서를 열어주세요.")
        log.close()
        return None

    log_print("✓ 한글 연결 성공\n")

    # 2. 테이블 스캔
    log_print("[2단계] 문서 내 테이블 스캔 중...")
    manager = TableManager(hwp)
    tables = manager.scan_tables()

    if not tables:
        log_print("✗ 문서에 테이블이 없습니다.")
        log.close()
        return []

    log_print(f"✓ {len(tables)}개의 테이블 발견\n")

    # 3. 테이블 목록 출력
    log_print("[3단계] 발견된 테이블 목록:")
    for i, t in enumerate(tables):
        log_print(f"  {i}. 테이블 (Para={t['para']})")
    log_print()

    # 4. 작성자 정보 설정
    author_info = {
        'created_by': AUTHOR_NAME,
        'description': 'Auto-generated by batch script'
    }

    # 5. 모든 테이블에 누름틀 삽입
    log_print("[4단계] 모든 테이블에 누름틀 삽입 시작\n")

    results = []

    for i, table in enumerate(tables):
        # 인덱스로 테이블 컨트롤 가져오기
        table_ctrl = manager.get_table_by_index(i)
        table_id = f"TBL{i+1:03d}"  # TBL001, TBL002, ...

        log_print(f"{'─' * 60}")
        log_print(f"테이블 {i+1}/{len(tables)} 처리 중 (ID: {table_id})")
        log_print(f"{'─' * 60}")

        # 누름틀 삽입 (로그 출력은 insert_structured_fields 내부에서 처리)
        # stdout을 로그 파일로 임시 리다이렉트
        old_stdout = sys.stdout
        sys.stdout = log

        result = manager.insert_structured_fields(
            table_ctrl,
            table_id,
            HEADER_ROWS,
            FOOTER_ROWS,
            author_info
        )

        sys.stdout = old_stdout

        # 결과 저장
        results.append({
            'table_index': i,
            'table_id': table_id,
            'result': result
        })

        # YAML 파일로 저장
        yaml_path = f"table_{table_id}_structure.yaml"
        save_data = {
            'author_info': result['author_info'],
            'metadata': result['metadata'],
            'header': {str(k): v for k, v in result['header'].items()},
            'body': {str(k): v for k, v in result['body'].items()},
            'footer': {str(k): v for k, v in result['footer'].items()}
        }

        with open(yaml_path, 'w', encoding='utf-8') as f:
            yaml.dump(save_data, f, allow_unicode=True, default_flow_style=False)

        log_print(f"✓ 구조 정보 저장: {yaml_path}")
        log_print()

    # 6. 전체 요약
    log_print("=" * 60)
    log_print("  완료 요약")
    log_print("=" * 60)
    log_print(f"✓ 처리된 테이블: {len(results)}개")

    total_fields = 0
    for r in results:
        table_result = r['result']
        count = len(table_result['header']) + len(table_result['body']) + len(table_result['footer'])
        total_fields += count
        log_print(f"  - {r['table_id']}: {count}개 누름틀 삽입")

    log_print(f"\n✓ 총 삽입된 누름틀: {total_fields}개")
    log_print(f"\n로그 저장 위치: {log_file}")
    log_print()

    log.close()
    return results


if __name__ == "__main__":
    print()
    results = main()
    print("\n프로그램 종료")
